version: '3'
services:
  compiler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
        USER_PASSWORD: ${USER_PASSWORD}
    container_name: rtt-esp
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: /home/rtt
    volumes:
      - ../../:/home/rtt/rtt
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    entrypoint:
      - bash
    stdin_open: true
    tty: true
